import math
import pandas as pd


def summarize_trades(log_path: str = "trading_log.csv") -> dict:
    """Return basic statistics for a trading log.

    Parameters
    ----------
    log_path : str, optional
        Path to ``trading_log.csv`` generated by the environment.

    Returns
    -------
    dict
        Dictionary with total number of trades, counts of winning and
        losing trades, overall PnL and the win/loss ratio.
    """
    log = pd.read_csv(log_path)

    trades = log[log["realized_pnl"] != 0]
    total = len(trades)
    winning = (trades["realized_pnl"] > 0).sum()
    losing = (trades["realized_pnl"] < 0).sum()
    total_pnl = trades["realized_pnl"].sum()

    if losing == 0:
        ratio = math.inf if winning > 0 else 0.0
    else:
        ratio = winning / losing

    return {
        "total_trades": int(total),
        "winning_trades": int(winning),
        "losing_trades": int(losing),
        "total_pnl": float(total_pnl),
        "win_loss_ratio": ratio,
    }
