api_key: "YOUR_MEXC_API_KEY"
api_secret: "YOUR_MEXC_API_SECRET"

symbols:
  - BTCUSDT
  - ETHUSDT

train:
  window_size: 60
  total_timesteps: 100000

live_trading:
  take_profit: 0.05  # 5% gain
  stop_loss: 0.02    # 2% loss
  invest_ratio: 0.1  # 10% of available balance
