symbols:
  - DOGEEUR
  - PEPEEUR

strategies:
  ma_rsi:
    indicators: [rsi, ma]
  macd_atr_stochrsi:
    indicators: [macd, macd_signal, macd_hist, atr, stochrsi]
  bollinger_bands:
    indicators: [bb_lower, bb_middle, bb_upper]

default_strategy: ma_rsi

train:
  window_size: 60
  total_timesteps: 100000
  device: cpu

rewards:
  hold: 0
  buy: 1
  profit_multiplier: 10
  loss_multiplier: 20
