api_key: "mx0vglqvS3YIffZCvA"
api_secret: "d2a8b7bb5cfa43ed94b08b125b2f60fe"

spot_trading:
  - symbol: "BTCUSDT"
    window_size: 60
    training_budget: 100
    take_profit_pct: 10
    stop_loss_pct: 2

  - symbol: "ETHUSDT"
    window_size: 60
    training_budget: 50
    take_profit_pct: 10
    stop_loss_pct: 2

use_testnet: false
log_file: "data/trading_log.csv"